
Vagrant.configure("2") do |config|


  config.vm.define "ubuntu" do |u|
	u.vm.box = "ubuntu/bionic64"
	u.vm.provision :shell, path: "bootstrap.sh"
	u.vm.network :forwarded_port, guest: 80, host: 8080
	u.vm.network "private_network", ip: "192.168.50.4"

    u.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
    end
  end

  config.vm.define "debian" do |d|
	d.vm.box = "generic/debian10"
	d.vm.provision :shell, path: "bootstrap2.sh"
	d.vm.network "private_network", ip: "192.168.50.5"

	d.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
  end

  
end
